modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.mirdamod]]
    modId="neoforge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mirdamod]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
